#!/bin/bash

# Exit on command errors and treat unset variables as an error
set -eu

# Load common variables and functions
source ./_common.sh

# Retrieve arguments
domain=$YNH_APP_ARG_DOMAIN
path=$YNH_APP_ARG_PATH
gogsrepo=$YNH_APP_ARG_GOGSREPO
is_public=$YNH_APP_ARG_IS_PUBLIC

# Save app settings
ynh_app_setting_set "$app" gogsrepo "$gogsrepo"
ynh_app_setting_set "$app" is_public "$is_public"

pre_install $gogsrepo

# Clone the repo
sudo git clone $repo_path $DESTDIR
sudo chown -R gogs:gogs $DESTDIR

# Install the app
install_site $domain $path $gogsrepo $is_public
