#!/bin/bash

# Exit on command errors and treat unset variables as an error
set -eu

# Load common variables and functions
source ./_common.sh

# Retrieve old app settings
domain=$(ynh_app_setting_get "$app" domain)
path=$(ynh_app_setting_get "$app" path)
gogsrepo=$(ynh_app_setting_get "$app" gogsrepo)

pre_install $gogsrepo --restore

# Restore NGINX configuration
sudo cp -a ./nginx.conf "/etc/nginx/conf.d/${domain}.d/${app}.conf"

# Restart webserver
sudo systemctl reload nginx.service
