#!/bin/bash

# Exit on command errors and treat unset variables as an error
set -eu

# Load common variables and functions
source ./_common.sh

# Retrieve old app settings
domain=$(ynh_app_setting_get "$app" domain)
gogsrepo=$(ynh_app_setting_get "$app" gogsrepo)

pre_install $gogsrepo

# Restore the app and data files
sudo cp -a ./www "$DESTDIR"
# Restore directories and permissions
sudo chown -R "gogs:gogs" "$DESTDIR"

# Restore git hook
sudo cp a ./post-receive $repo_path"/hooks/post-receive"
sudo chmod +x $repo_path"/hooks/post-receive"
sudo chown -R gogs:gogs $repo_path

# Restore NGINX configuration
sudo cp -a ./nginx.conf "/etc/nginx/conf.d/${domain}.d/${app}.conf"

# Restart webserver
sudo systemctl reload nginx.service
