#!/bin/bash

# Exit on command errors and treat unset variables as an error
set -eu

# Load common variables and functions
source ./_common.sh

# Retrieve app settings
domain=$(ynh_app_setting_get "$app" domain)
path=$(ynh_app_setting_get "$app" path)
gogsrepo=$(ynh_app_setting_get "$app" gogsrepo)
repo_branch=$(ynh_app_setting_get "$app" repo_branch)
repo_dir=$(ynh_app_setting_get "$app" repo_dir)
is_public=$(ynh_app_setting_get "$app" is_public)

repo_path="/home/gogs/repositories/"$gogsrepo".git"

# Install the app
install_site $domain $path $repo_path $repo_branch $repo_dir $is_public

# Update the repo
sudo git --work-tree=$DESTDIR --git-dir=$repo_path checkout $repo_branch -f > /dev/null 2>&1
sudo chown -R gogs:gogs $DESTDIR
